//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.CalculatorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://pragimtech.com/webservices", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pragimtech.com/webservices", ConfigurationName="CalculatorService.CalculatorWebServiceSoap")]
    public interface CalculatorWebServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (add_x0020_two_x0020_numbers) of message add_x0020_two_x0020_numbers does not match the default value (Add)
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/add two numbers", ReplyAction="*")]
        CalculatorWebApplication.CalculatorService.addtwonumbers1 Add(CalculatorWebApplication.CalculatorService.addtwonumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/add two numbers", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.addtwonumbers1> AddAsync(CalculatorWebApplication.CalculatorService.addtwonumbers request);
        
        // CODEGEN: Generating message contract since the wrapper name (Add) of message AddRequest does not match the default value (Add1)
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/Add", ReplyAction="*")]
        CalculatorWebApplication.CalculatorService.AddResponse Add1(CalculatorWebApplication.CalculatorService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.AddResponse> Add1Async(CalculatorWebApplication.CalculatorService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name GetCalculationsResult from namespace http://pragimtech.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/GetCalculations", ReplyAction="*")]
        CalculatorWebApplication.CalculatorService.GetCalculationsResponse GetCalculations(CalculatorWebApplication.CalculatorService.GetCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pragimtech.com/webservices/GetCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.GetCalculationsResponse> GetCalculationsAsync(CalculatorWebApplication.CalculatorService.GetCalculationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add two numbers", WrapperNamespace="http://pragimtech.com/webservices", IsWrapped=true)]
    public partial class addtwonumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pragimtech.com/webservices", Order=0)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pragimtech.com/webservices", Order=1)]
        public int secondNum;
        
        public addtwonumbers() {
        }
        
        public addtwonumbers(int firstNum, int secondNum) {
            this.firstNum = firstNum;
            this.secondNum = secondNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add two numbersResponse", WrapperNamespace="http://pragimtech.com/webservices", IsWrapped=true)]
    public partial class addtwonumbers1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="add_x0020_two_x0020_numbersResult", Namespace="http://pragimtech.com/webservices", Order=0)]
        public int addtwonumbersResult;
        
        public addtwonumbers1() {
        }
        
        public addtwonumbers1(int addtwonumbersResult) {
            this.addtwonumbersResult = addtwonumbersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://pragimtech.com/webservices", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pragimtech.com/webservices", Order=0)]
        public int firstNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pragimtech.com/webservices", Order=1)]
        public int secondNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pragimtech.com/webservices", Order=2)]
        public int thirdNum;
        
        public AddRequest() {
        }
        
        public AddRequest(int firstNum, int secondNum, int thirdNum) {
            this.firstNum = firstNum;
            this.secondNum = secondNum;
            this.thirdNum = thirdNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://pragimtech.com/webservices", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pragimtech.com/webservices", Order=0)]
        public int AddResult;
        
        public AddResponse() {
        }
        
        public AddResponse(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculations", Namespace="http://pragimtech.com/webservices", Order=0)]
        public CalculatorWebApplication.CalculatorService.GetCalculationsRequestBody Body;
        
        public GetCalculationsRequest() {
        }
        
        public GetCalculationsRequest(CalculatorWebApplication.CalculatorService.GetCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCalculationsRequestBody {
        
        public GetCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCalculationsResponse", Namespace="http://pragimtech.com/webservices", Order=0)]
        public CalculatorWebApplication.CalculatorService.GetCalculationsResponseBody Body;
        
        public GetCalculationsResponse() {
        }
        
        public GetCalculationsResponse(CalculatorWebApplication.CalculatorService.GetCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pragimtech.com/webservices")]
    public partial class GetCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CalculatorWebApplication.CalculatorService.ArrayOfString GetCalculationsResult;
        
        public GetCalculationsResponseBody() {
        }
        
        public GetCalculationsResponseBody(CalculatorWebApplication.CalculatorService.ArrayOfString GetCalculationsResult) {
            this.GetCalculationsResult = GetCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorWebServiceSoapChannel : CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorWebServiceSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap>, CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap {
        
        public CalculatorWebServiceSoapClient() {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculatorService.addtwonumbers1 CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.Add(CalculatorWebApplication.CalculatorService.addtwonumbers request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int firstNum, int secondNum) {
            CalculatorWebApplication.CalculatorService.addtwonumbers inValue = new CalculatorWebApplication.CalculatorService.addtwonumbers();
            inValue.firstNum = firstNum;
            inValue.secondNum = secondNum;
            CalculatorWebApplication.CalculatorService.addtwonumbers1 retVal = ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).Add(inValue);
            return retVal.addtwonumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.addtwonumbers1> CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.AddAsync(CalculatorWebApplication.CalculatorService.addtwonumbers request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.addtwonumbers1> AddAsync(int firstNum, int secondNum) {
            CalculatorWebApplication.CalculatorService.addtwonumbers inValue = new CalculatorWebApplication.CalculatorService.addtwonumbers();
            inValue.firstNum = firstNum;
            inValue.secondNum = secondNum;
            return ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculatorService.AddResponse CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.Add1(CalculatorWebApplication.CalculatorService.AddRequest request) {
            return base.Channel.Add1(request);
        }
        
        public int Add1(int firstNum, int secondNum, int thirdNum) {
            CalculatorWebApplication.CalculatorService.AddRequest inValue = new CalculatorWebApplication.CalculatorService.AddRequest();
            inValue.firstNum = firstNum;
            inValue.secondNum = secondNum;
            inValue.thirdNum = thirdNum;
            CalculatorWebApplication.CalculatorService.AddResponse retVal = ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).Add1(inValue);
            return retVal.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.AddResponse> CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.Add1Async(CalculatorWebApplication.CalculatorService.AddRequest request) {
            return base.Channel.Add1Async(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.AddResponse> Add1Async(int firstNum, int secondNum, int thirdNum) {
            CalculatorWebApplication.CalculatorService.AddRequest inValue = new CalculatorWebApplication.CalculatorService.AddRequest();
            inValue.firstNum = firstNum;
            inValue.secondNum = secondNum;
            inValue.thirdNum = thirdNum;
            return ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).Add1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculatorService.GetCalculationsResponse CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.GetCalculations(CalculatorWebApplication.CalculatorService.GetCalculationsRequest request) {
            return base.Channel.GetCalculations(request);
        }
        
        public CalculatorWebApplication.CalculatorService.ArrayOfString GetCalculations() {
            CalculatorWebApplication.CalculatorService.GetCalculationsRequest inValue = new CalculatorWebApplication.CalculatorService.GetCalculationsRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.GetCalculationsRequestBody();
            CalculatorWebApplication.CalculatorService.GetCalculationsResponse retVal = ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).GetCalculations(inValue);
            return retVal.Body.GetCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.GetCalculationsResponse> CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap.GetCalculationsAsync(CalculatorWebApplication.CalculatorService.GetCalculationsRequest request) {
            return base.Channel.GetCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculatorService.GetCalculationsResponse> GetCalculationsAsync() {
            CalculatorWebApplication.CalculatorService.GetCalculationsRequest inValue = new CalculatorWebApplication.CalculatorService.GetCalculationsRequest();
            inValue.Body = new CalculatorWebApplication.CalculatorService.GetCalculationsRequestBody();
            return ((CalculatorWebApplication.CalculatorService.CalculatorWebServiceSoap)(this)).GetCalculationsAsync(inValue);
        }
    }
}
